name: Deploy Laravel 11 Project on Push
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get the latest code
      - name: Checkout the code
        uses: actions/checkout@v4

      # Step 2: Set up PHP and Node
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Laravel 11 requires PHP 8.2 or higher

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust to your Node version if needed

      # Step 3: Install Composer Dependencies
      - name: Install PHP Dependencies
        run: composer install --optimize-autoloader --no-dev --ignore-platform-reqs

      # Step 4: Install Node.js Dependencies
      - name: Install Node Dependencies
        run: npm install

      # Step 5: Build Assets (if your project uses assets like in Laravel Mix or Vite)
      - name: Build Assets
        run: npm run build

      # Step 6: Generate the Storage Link
      - name: Generate Storage Link
        run: php artisan storage:link

      # Step 7: Set Directory Permissions
      - name: Set Permissions
        run: chmod -R 777 storage bootstrap/cache

      # Step 8: Sync with FTP server
      - name: 📂 Sync Fast Solutions
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          local-dir: ./
